variable "azure_credentials_file" {
  description = "JSON Account Credentials file for Azure"
  default = "credentials.publishsettings"
}

variable "virtual_network_cidr" {
  description = "CIDR for the virtual network"
  default     = "10.0.0.0/16"
}

variable "bastion_cidr" {
  description = "CIDR for bastion network"
  default = "10.0.0.0/24"
}

variable "cf_cidr" {
  description = "CIDR for cloudfoundry network"
  default = "10.0.0.0/24"
}

variable "bosh_public_ip" {
  description = "Public IP for microbosh. "
}

variable "azure_subscription_id" {
  description = "Azure subscription id (comes from 'azure account list')"
}
variable "azure_tenant_id" {
  description = "Azure tenant id (comes from 'azure account list')"
}
variable "azure_client_id" {
  description = "Azure client id (comes from the bosh app creation)"
}
variable "azure_client_secret" {
  description = "Azure client id (generated by us)"
}
